Update: 05/27/24 04:58

diff --git a/tacOS/airootfs/etc/skel/.local/bin/08_setup_initramfs b/tacOS/airootfs/etc/skel/.local/bin/08_setup_initramfs
--- a/tacOS/airootfs/etc/skel/.local/bin/08_setup_initramfs
+++ b/tacOS/airootfs/etc/skel/.local/bin/08_setup_initramfs
@@ -1,19 +1,19 @@
 #!/bin/bash
-#shellcheck disable=SC2162
-#shellcheck disable=SC2143
-installreqsFunc() {
+#shellcheck disable=SC2162,SC2143
+
+install_reqs_func(){
 	local PACKAGES PKG BTCHSIZE BATCH
 	PACKAGES=(
-		"grub"
-		"mkinitcpio"
+		'grub'
+		'mkinitcpio'
 	)
 	BTCHSIZE=9
-	echo -e "#\n# installing requirements\n#"
-	for ((i = 0; i < "${#PACKAGES[@]}"; i += BTCHSIZE)); do
+	echo -e '\nInstalling requirements\n'
+	for ((i = 0; i < ${#PACKAGES[@]}; i += BTCHSIZE)); do
 		BATCH=("${PACKAGES[@]:i:BTCHSIZE}")
 		sudo pacman -S --noconfirm --needed "${BATCH[@]}" || {
 			for PKG in "${BATCH[@]}"; do
-				echo -e "#\n# ⚠ failed to install $PKG  ⚠\n#" |
+				echo -e '\nFailed to install $PKG ⚠\n' |
 				tee -a "$HOME/blderr.txt"
 			done
 		}
@@ -22,101 +22,110 @@ installreqsFunc() {
 	sudo pacman -Fy
 	sleep 1
 }
-setupmknitcpioFunc() {
+
+setup_mkinitcpio_func(){
 	local KERNELMTIME INITRAMFSMTIME ANS
-	KERNELMTIME=$(stat -c %Y "/boot/vmlinuz-linux")
-	INITRAMFSMTIME=$(stat -c %Y "/boot/initramfs-linux.img")
+	KERNELMTIME=$(stat -c %Y '/boot/vmlinuz-linux')
+	INITRAMFSMTIME=$(stat -c %Y '/boot/initramfs-linux.img')
 	if [ "$INITRAMFSMTIME" -gt "$KERNELMTIME" ]; then
-		echo -e "#\n# ramdisk is up to date\n#"
-		echo -e "# (c) cancel\n# (g) generate anyway\n#"
-		read -p "# ▸ " ANS
-		if [ "$ANS" == "c" ]; then
-			return 0
+		echo -e '\nRamdisk is up to date\n'
+		echo -e '~ <C> Cancel\n~ <G> Generate anyway\n'
+		read -p '~ ' ANS
+		if [ "$ANS" == 'c' ]; then return 0
 		else
-			echo -e "#\n# this will overwrite the existing ramdisk\n#"
-			echo -e "#\n# continue?\n#"
-			read -p "# ▸ " ANS
+			echo -e '\nThis will overwrite the existing ramdisk\n'
+			echo -e 'Continue?\n'
+			read -p '~' ANS
 			if [[ "$ANS" =~ ^(1|y|ya|ye|ta|ok|pl|th).* ]]; then
-				sudo mkinitcpio -P --generate "/boot/initramfs-linux.img"
+				sudo mkinitcpio -P
 			else return 0
 			fi
 		fi
 	else
-		echo -e "#\n# ramdisk older than kernel image"
-		echo -e "#\n# generating new initramfs image\n#"
-		echo -e "# this will overwrite the existing ramdisk\n#"
-		echo -e "#\n# continue?\n#"
-		read -p "# ▸ " ANS
+		echo -e '\nRamdisk older than kernel image'
+		echo -e '\nGenerating new initramfs image\n'
+		sleep 1
+		echo -e 'This will overwrite the existing ramdisk\n'
+		sleep 1
+		echo -e 'Continue?\n'
+		read -p '~ ' ANS
 		if [[ "$ANS" =~ ^(1|y|ya|ye|ta|ok|pl|th).* ]]; then
-			sudo mkinitcpio -P --generate "/boot/initramfs-linux.img"
-		else
-			return 0
+			sudo mkinitcpio -P
+		else return 0
 		fi
 	fi
 }
-setupgrubFunc() {
-	local TARGET TARGET GRUBARGS ANS
+
+setup_grub_func(){
+	local TARGETS TARGET GRUBARGS ANS
 	TARGETS=(
-		"arm-coreboot"
-		"arm-efi"
-		"arm-uboot"
-		"arm64-efi"
-		"i386-coreboot"
-		"i386-efi"
-		"i386-ieee1275"
-		"i386-multiboot"
-		"i386-pc"
-		"i386-qemu"
-		"i386-xen"
-		"i386-xen_pvh"
-		"ia64-efi"
-		"loongarch64-efi"
-		"mips-arc"
-		"mips-qemu_mips"
-		"mipsel-arc"
-		"mipsel-loongson"
-		"mipsel-qemu_mips"
-		"powerpc-ieee1275"
-		"riscv32-efi"
-		"riscv64-efi"
-		"sparc64-ieee1275"
-		"x86_64-efi (default)"
-		"x86_64-xen"
+		'arm-coreboot'
+		'arm-efi'
+		'arm-uboot'
+		'arm64-efi'
+		'i386-coreboot'
+		'i386-efi'
+		'i386-ieee1275'
+		'i386-multiboot'
+		'i386-pc'
+		'i386-qemu'
+		'i386-xen'
+		'i386-xen_pvh'
+		'ia64-efi'
+		'loongarch64-efi'
+		'mips-arc'
+		'mips-qemu_mips'
+		'mipsel-arc'
+		'mipsel-loongson'
+		'mipsel-qemu_mips'
+		'powerpc-ieee1275'
+		'riscv32-efi'
+		'riscv64-efi'
+		'sparc64-ieee1275'
+		'x86_64-efi (default)'
+		'x86_64-xen'
 	)
-	GRUBARGS=(--efi-directory="/boot/efi")
-	if [ $(tree "/boot/efi" | grep "grub") ]; then
+	GRUBARGS=(--efi-directory='/boot/efi')
+	if ! tree '/boot/efi' | grep -q 'grub'; then
 		while true; do
-			echo -e "#\n# grub isnt installed in /boot/efi"
-			echo -e "#\n# (l) list targets\n# (e) enter target"
-			echo -e "# (d) use default\n# (c) cancel\n#"
-			read -p "# ▸ " ANS
-			if [ "$ANS" == "l" ]; then
-				for TARGET in "${TARGETS[@]}"; do echo " $TARGET" | less
-				done
-			elif [ "$ANS" == "e" ]; then
-				echo -e "#\n# enter target\n#"
-				read -r -p "# ▸ " ANS
-				for ARG in "${GRUBARGS[@]}"; do
-					sudo grub-install --target="$ANS" "$ARG"
-				done; break
-			elif [ "$ANS" == "d" ]; then
-				for ARG in "${GRUBARGS[@]}"; do
-					sudo grub-install --target="x86_64-efi" "$ARG"
-				done; break
-			elif [ "$ANS" == "c" ]; then break
-			fi
+			echo -e '\nGrub isnt installed in /boot/efi\n'
+			echo -e '~ <L> List targets\n~ <E> Enter target'
+			echo -e '~ <D> Use default\n~ <C> Cancel\n'
+			read -p '~ ' ANS
+			case $ANS in
+				l)
+					for TARGET in "${TARGETS[@]}"; do
+						echo " $TARGET"
+					done | less;;
+				e)
+					echo -e '\nEnter target\n'
+					read -rp '~ ' ANS
+					for ARG in "${GRUBARGS[@]}"; do
+						sudo grub-install --target="$ANS" "$ARG"
+					done
+					break;;
+				d)
+					for ARG in "${GRUBARGS[@]}"; do
+						sudo grub-install --target='x86_64-efi' "$ARG"
+					done
+					break;;
+				c)
+					break;;
+			esac
 		done
-		if ! test -f "/boot/grub/grub.cfg"; then 
-			echo -e "#\n# this system doesnt have a grub config"
-			echo -e "#\n# generating a new one at /boot/grub/grub.cfg"
-			sudo grub-mkconfig -o "/boot/grub/grub.cfg"
-			sudo update-grub
-		fi
 	fi
+	if [ ! -f '/boot/grub/grub.cfg' ]; then
+		echo -e '\nThis system doesnt have a grub config'
+		sleep 1
+		echo -e '\nGenerating a new one at /boot/grub/grub.cfg'
+		sudo grub-mkconfig -o '/boot/grub/grub.cfg'
+		sudo update-grub
+	fi; echo
 }
+
 if [ -n "$1" ]; then "$1"
 else
-	installreqsFunc
-	setupmknitcpioFunc
-	setupgrubFunc
+	install_reqs_func
+	setup_mkinitcpio_func
+	setup_grub_func
 fi
diff --git a/tacOS/airootfs/etc/skel/.local/bin/09_setup_extras b/tacOS/airootfs/etc/skel/.local/bin/09_setup_extras
--- a/tacOS/airootfs/etc/skel/.local/bin/09_setup_extras
+++ b/tacOS/airootfs/etc/skel/.local/bin/09_setup_extras
@@ -1,16 +1,16 @@
 #!/bin/bash
+
 LOGFILE="$HOME/extras.log"
 ! test -e "$LOGFILE" && touch "$LOGFILE"
 
 ALIENURL='https://sourceforge.net/projects/alien-pkg-convert/files/release/alien_8.95.tar.xz'
-DUMMYURL='https://github.com/c0rNCh1p/dummy.git'
-EGGROLLURL='https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases/latest'
+DUMMYURL='https://github.com/c0rnch1p/dummy.git'
 FABLAURL='https://github.com/openAVproductions/openAV-Fabla2.git'
-GH0STYURL='https://github.com/c0rNCh1p/gh0sty.git'
+GH0STYURL='https://github.com/c0rnch1p/gh0sty.git'
 MINIMAPURL='https://github.com/johnfactotum/gedit-restore-minimap.git'
-SCUTTLEURL='https://github.com/c0rNCh1p/scuttle.git'
+SCUTTLEURL='https://github.com/c0rnch1p/scuttle.git'
 
-nottyOrNoice(){
+install_reqs(){
 	local NAUGHTYORNICE BTCHSIZE BATCH
 	NAUGHTYORNICE=(
 		'alhp-keyring'
@@ -25,186 +25,155 @@ nottyOrNoice(){
 		'wireshark-cli'
 	)
 	BTCHSIZE=9
-	echo -e '|\n|~ Installing a doorknob\n|'
-	for ((i=0; i < "${#NAUGHTYORNICE[@]}"; i += BTCHSIZE)); do
+	echo -e 'Installing requirements\n'
+	for ((i = 0; i < ${#NAUGHTYORNICE[@]}; i += BTCHSIZE)); do
 		BATCH=("${NAUGHTYORNICE[@]:i:BTCHSIZE}")
 		sudo pacman -S --noconfirm --needed "${BATCH[@]}" || {
 			for PKG in "${BATCH[@]}"; do
-				echo -e "|\n|~ ⚠ Failed to install $PKG  ⚠\n|" | tee -a "$LOGFILE"
+				echo -e "\nFailed to install $PKG\n" | tee -a "$LOGFILE"
 			done
 		}
 	done
-	sudo pacman -Syu; sudo pacman -Fy; sleep 1
+	sudo pacman -Syu
+	sudo pacman -Fy
+	sleep 1
 }
 
-bldAURPkgs(){
-	local AURPKGS BTCHSIZE BATCH
+install_aur_pkgs(){
+	local AURPKGS PKG
 	AURPKGS=(
-		'aview'
 		'awesome-freedesktop-git'
 		'awesome-themes-git'
-		'bgrm-git'
 		'deadbeef-plugin-statusnotifier-git'
 		'die-plugins'
 		'epson-inkjet-printer-escpr'
 		'epson-inkjet-printer-escpr2'
 		'gedit-dark-variant'
 		'gedit-open-uri-context-menu-git'
-		'habash'
 		'lain-git'
 		'material-black-colors-theme'
 		'nemo-compare'
-		'python-habitica'
 		'rig'
 		'sl'
 		'steamcmd'
 		'sticky-notes'
 		'unfatarians-studio'
 	)
-	BTCHSIZE=9
-	echo -e "|\n|~ Installing AUR packages: ${#AURPKGS[@]}\n|"
-	for ((i=0; i < "${#AURPKGS[@]}"; i += BTCHSIZE)); do
-		BATCH=("${AURPKGS[@]:i:BTCHSIZE}")
-		yay -S --noconfirm --needed --mflags --skipinteg "${BATCH[@]}" || {
-			for PKG in "${BATCH[@]}"; do
-				echo -e "|\n|~ ⚠ Failed to install $PKG  ⚠\n|" | tee -a "$LOGFILE"
-			done
-		}
+	echo -e "\nInstalling AUR packages: ${#AURPKGS[@]}\n"
+	for PKG in "${AURPKGS[@]}"; do
+		if ! yay -S --noconfirm --needed --mflags --skipinteg "$PKG"; then
+			echo -e "\nFailed to install $PKG\n" | tee -a "$LOGFILE"
+		else
+			echo -e "\nSuccessfully installed $PKG\n" | tee -a "$LOGFILE"
+		fi
 	done
-	yay; yay -Fy; sleep 1
+	yay
+	yay -Fy
+	sleep 1
 }
 
-bldDummy(){
-	pullDummy(){
-		git clone "$DUMMYURL"
-		cd 'dummy' || return 1
-		make install
-	}
-	echo -e '|\n|~ Building Dummy\n|'
-	cd "$DATA" || cd "$HOME/.local/share/" || return 1
-	if [ ! -d "$HOME/.local/share/dummy" ]; then pullDummy
-	elif [ -d "$HOME/.local/share/dummy" ]; then sudo rm -r 'dummy'; pullDummy
-	fi; cd || return 1
-}
-
-bldGh0sty(){
-	pullGh0sty(){
-		git clone "$GH0STYURL"
-		cd 'gh0sty' || return 1
-		chmod 764 'install.sh'
-		./'install.sh'
-	}	
-	echo -e '|\n|~ Building Gh0sty\n|'
-	cd "$DATA" || cd "$HOME/.local/share/" || return 1
-	if [ ! -d "$HOME/.local/share/gh0sty" ]; then pullGh0sty
-	elif [ -d "$HOME/.local/share/dummy" ]; then sudo rm -r 'gh0sty'; pullGh0sty
-	fi; cd || return 1
-}
-
-bldScuttle(){
-	pullScuttle(){
-		git clone "$SCUTTLEURL"
-		cd 'scuttle' || return 1
-		chmod 764 'install.sh'
-		./'install.sh'
-	}
-	echo -e '|\n|~ Building Scuttle\n|'
-	cd "$DATA" || cd "$HOME/.local/share/" || return 1
-	if [ ! -d "$HOME/.local/share/scuttle" ]; then pullScuttle
-	elif [ -d "$HOME/.local/share/dummy" ]; then sudo rm -r 'scuttle'; pullScuttle
-	fi; cd || return 1
-}
-
-bldFabla(){
-	pullFabla(){
-		git clone "$FABLAURL"
-		cd 'openAV-Fabla2/' || return 1
-		mkdir build; cd build || return 1
-		cmake ..; make -j4
-		sudo make install
-	}
-	echo -e '|\n|~ Building fabla2\n|'
-	cd "$DATA" || cd "$HOME/.local/share/" || return 1
-	if [[ ! -d "$FABLA_HOME" || -d "$HOME/.local/share/openAV-Fabla2" ]]; then pullFabla
-	elif [[ -d "$FABLA_HOME" || -d "$HOME/.local/share/openAV-Fabla2" ]]; then
-		cd "$FABLA_HOME" || cd "$HOME/.local/share/openAV-Fabla2" || return 1
-		if [[ $(git diff 'origin/master') ]]; then 
-			cd .. || return 1
-			sudo rm -r 'openAV-Fabla2'; pullFabla
-		fi
-	fi; cd || return 1
-}
-
-bldGeditMinimap(){
-	echo -e '|\n|~ Building Gedit Minimap\n|'
-	cd "$DATA" || cd "$HOME/.local/share/" || return 1
-	if [[ ! -d "$GEDIT_HOME/plugins" || -d "$HOME/.local/share/gedit/plugins" ]]; then 
-		mkdir -p "$GEDIT_HOME/plugins" || mkdir -p "$HOME/.local/share/gedit/plugins"
+build_dummy(){
+	echo -e '\nBuilding Dummy\n'
+	cd "$HOME/.local/share" || return 1
+	if [ -d 'dummy' ]; then
+		sudo rm -r dummy
 	fi
-	if [[ ! -d "$GEDIT_HOME/plugins/restore-minimap" || -d "$HOME/.local/share/gedit/plugins/restore-minimap" ]]; then
-		cd "$GEDIT_HOME/plugins" || "$HOME/.local/share/gedit/plugins/restore-minimap" || return 1
-		git clone "$MINIMAPURL" restore-minimap
-	elif [[ -d "$GEDIT_HOME/plugins/restore-minimap" || -d "$HOME/.local/share/gedit/plugins/restore-minimap" ]]; then 
-		cd "$GEDIT_HOME/plugins/restore-minimap" || "$HOME/.local/share/gedit/plugins/restore-minimap" || return 1
-		if [[ $(git diff 'origin/master') ]]; then
-			cd .. || return 1
-			sudo rm -r 'restore-minimap'
-			git clone "$MINIMAPURL" restore-minimap
-		fi
-	fi; cd || return 1
+	git clone "$DUMMYURL" dummy
+	cd dummy || return 1
+	make install
+	cd || return 1
 }
 
-bldAlien(){
-	pullAlien(){
-		wget "$ALIENURL"
-		tar -xvJf 'alien'*'.tar.xz'
-		sudo rm 'alien'*'.tar.xz'
-	}
-	makeAlien(){
-		cd "$ALIEN_HOME" || return 1
-		perl 'Makefile.PL'; make
-		sudo make install
-		sudo cp '/bin/site_perl/alien' '/bin/alien'
-	}
-	echo -e '|\n|~ Building Alien Converter\n|'
-	cd "$DATA" || cd "$HOME/.local/share/" || return 1
-	if [ ! -d "$ALIEN_HOME" ]; then pullAlien; mv 'alien'* 'alien'; makeAlien
-	elif [ -d "$ALIEN_HOME" ]; then pullAlien
-		if [[ $(diff "$ALIEN_HOME" 'alien'*) ]]; then 
-			sudo rm -r 'alien'; mv 'alien'* 'alien'; makeAlien
-		else sudo rm -r alien*
-		fi
-	fi; cd || return 1
-}
-
-bldGloriousEggroll(){
-	#set -euo pipefail
-	echo -e '|\n|~ Building Glorious Eggroll\n|'
-	if [[ ! -d '/tmp/proton-ge-custom' ]]; then
-		rm -rf '/tmp/proton-ge-custom'
-		mkdir -p '/tmp/proton-ge-custom'
+build_gh0sty(){
+	echo -e '\nBuilding Gh0sty\n'
+	cd "$HOME/.local/share" || return 1
+	if [ -d 'gh0sty' ]; then
+		sudo rm -r gh0sty
 	fi
-	cd '/tmp/proton-ge-custom' || return 1
-	curl -sLOJ "$(curl -s $EGGROLLURL | grep browser_download_url | cut -d\" -f4 | grep .tar.gz)"
-	curl -sLOJ "$(curl -s $EGGROLLURL | grep browser_download_url | cut -d\" -f4 | grep .sha512sum)"
-	sha512sum -c ./*'.sha512sum'
-	mkdir -p "$HOME/.steam/root/compatibilitytools.d"
-	tar -xf 'GE-Proton'*'.tar.gz' -C "$HOME/.steam/root/compatibilitytools.d/"
-	echo 'All done :)'
+	git clone "$GH0STYURL" gh0sty
+	cd gh0sty || return 1
+	chmod 764 install.sh
+	./install.sh
+	cd || return 1
+}
+
+build_scuttle(){
+	echo -e '\nBuilding Scuttle\n'
+	cd "$HOME/.local/share" || return 1
+	if [ -d 'scuttle' ]; then
+		sudo rm -r scuttle
+	fi
+	git clone "$SCUTTLEURL" scuttle
+	cd scuttle || return 1
+	chmod 764 install.sh
+	./install.sh
+	cd || return 1
+}
+
+build_fabla(){
+	echo -e '\nBuilding Fabla2\n'
+	cd "$HOME/.local/share" || return 1
+	if [ -d 'openAV-Fabla2' ]; then
+		sudo rm -r openAV-Fabla2
+	fi
+	git clone "$FABLAURL"
+	cd openAV-Fabla2 || return 1
+	mkdir build
+	cd build || return 1
+	cmake ..
+	make -j4
+	sudo make install
+	cd || return 1
+}
+
+build_gedit_minimap(){
+	echo -e '\nBuilding Gedit Minimap\n'
+	PLUGINS_DIR="$HOME/.local/share/gedit/plugins"
+	mkdir -p "$PLUGINS_DIR"
+	cd "$PLUGINS_DIR" || return 1
+	if [ -d 'restore-minimap' ]; then
+		sudo rm -r restore-minimap
+	fi
+	git clone "$MINIMAPURL" restore-minimap
+	cd || return 1
+}
+
+build_alien(){
+	echo -e 'Building Alien Converter\n'
+	cd "$HOME/.local/share" || return 1
+	if [ -d 'alien' ]; then
+		sudo rm -r alien
+	fi
+	wget "$ALIENURL"
+	tar -xvJf alien*.tar.xz
+	rm alien*.tar.xz
+	ALIEN_DIR=$(find . -maxdepth 1 -type d -name 'alien*')
+	if [ -n "$ALIEN_DIR" ]; then
+		mv "$ALIEN_DIR" alien
+		cd alien || return 1
+		perl Makefile.PL
+		make
+		sudo make install
+		sudo cp /bin/site_perl/alien /bin/alien
+		cd || return 1
+	else
+		echo 'Alien directory not found after extraction.'
+		return 1
+	fi
 }
 
 sudo mv "$LOGFILE" '/var/log'
-if [ -n "$1" ]; then "$1"
+if [ -n "$1" ]; then
+	"$1"
 else
-	nottyOrNoice
-	bldAURPkgs
-	bldDummy
-	bldGh0sty
-	bldScuttle
-	bldFabla
-	bldGeditMinimap
-	bldAlien
-	#bldGloriousEggroll
-fi
+	install_reqs
+	install_aur_pkgs
+	build_dummy
+	build_gh0sty
+	build_scuttle
+	build_fabla
+	build_gedit_minimap
+	build_alien
+fi; echo
 
-unset ALIENURL DUMMYURL EGGROLLURL FABLAURL GH0STYURL LOGFILE MINIMAPURL SCUTTLEURL
+unset ALIENURL DUMMYURL FABLAURL GH0STYURL LOGFILE MINIMAPURL SCUTTLEURL
